### ISSUE TITLE
[Bug]: Example systems with electrolyzers not properly configured

### ISSUE THREAD

**Issue by joe-rodden1** [GenXProject/GenX.jl#759] opened 2024-08-23 03:15 UTC
### Bug description

The inputs for the example systems (2 and 8) with electrolyzers do not appear properly configured for the latest code. The input files will not run at all as configured due to a missing Electrolyzer_Min_kt column in the Electrolyzer.csv files. Even after fixing these, the cases do not appear to be running properly. I'm either getting no electrolysis built (even when testing very low annual cost assumptions and high selling prices) or the cases are not solving at all (I unfortunately do not have CPLEX or Gurobi to check conflicts).

I wish I could provide more useful info but am pretty new to using this. I wonder if a set of new input files can be uploaded which are confirmed to work with the latest code.

### Environment and Version

MacOS, Julia 1.10, main branch v0.4.1

**Comment by lbonaldo** [comment] 2024-08-23 16:12
Hi @joe-rodden1, thank you for opening this issue. I’m happy to help you troubleshoot this. Could you please double-check the GenX version you're running? Here are some steps you can follow:
```julia
$ julia --project=<path/to/env/with/GenX>
julia> Type `]` to bring up the package system
pkg> st
```

**Comment by joe-rodden1** [comment] 2024-08-23 16:29
Yep, it's v0.4.1

Joe Rodden
Co-founder & CEO
Lydian ( https://www.lydianlabsinc.com/ )
630-215-6597

**Comment by lbonaldo** [comment] 2024-08-23 16:48
Could you please also share the error message together with the stacktrace?

**Comment by joe-rodden1** [comment] 2024-08-23 17:13
Luca, see attached:

* first file is the stack trace from running the files as-is

* second is after adding an Electrolyzer_Min_kt column to the resource (Electrolyzer.csv) file with a value of 0 and no other changes. I've also added the output files in the zip - you'll see no electrolysis is being built, which I imagine is not the intention of the test case for electrolysis

* To test above, changed the product value from 1000 to 5000 USD per tonne and the annual investment cost from 125,000 to 50,000. Runs, but still no electrolysis built (results in second zip file)

Joe Rodden
Co-founder & CEO
Lydian ( https://www.lydianlabsinc.com/ )
630-215-6597

**Comment by lbonaldo** [comment] 2024-08-23 17:44
@joe-rodden1, unfortunately, I haven't received the files yet. 
However, I checked the examples, and they seem to be working correctly. I think I was able to reproduce the error by running GenX <= v0.4.0 with the new examples. The `Electrolyzer_Min_kt` column in the Electrolyzer.csv file has been removed because GenX now retrieves that value from the `Hydrogen_demand.csv` policy file (you can see an example [here](https://github.com/GenXProject/GenX.jl/blob/main/example_systems/2_three_zones_w_electrolyzer/policies/Hydrogen_demand.csv)).
Could you please let me know how you're running GenX?

**Comment by joe-rodden1** [comment] 2024-08-23 18:07
Ah, I am just using the terminal command: julia Run.jl

I suppose the likely explanation then is that the GenX version being used by julia may be different. Is there a better way to run it that you recommend?

Joe Rodden
Co-founder & CEO
Lydian ( https://www.lydianlabsinc.com/ )
630-215-6597

**Comment by lbonaldo** [comment] 2024-08-23 18:44
The command `julia Run.jl` runs the `Run.jl` script (and therefore GenX) using the **base** Julia environment. You can verify this by running:
```
$ julia
pkg> status
```
Therefore, an easy fix would be to check (and if necessary, update) GenX in this environment by running:
```
$ julia
pkg> add/update GenX
```
However, my recommendation is to create a new Julia environment inside a folder you’re using to run the cases:
```
$ julia --project=.     # <---- This runs Julia within the environment defined in the current folder "."
pkg> add GenX   # Or use `pkg> update GenX` if needed
```
To run GenX installed in that environment, simply use the `--project` flag with the Julia command:
```
$ julia --project=. </path/to/Run.jl>
```
f you’re running multiple tests, I also suggest executing the cases within the same Julia REPL session using the `include` function:
```
$ julia --project=.
julia> include("/path/to/Run.jl")
julia> include("/path/to/Run2.jl")
```
In this way, the packages will be compiled within the same REPL, leading to improved performance.

https://genxproject.github.io/GenX.jl/dev/Getting_Started/examples_casestudies/#Example-cases

**Comment by joe-rodden1** [comment] 2024-08-24 01:24
Thanks, Luca. I was able to get the example case running now.

I'm still seeing weird results with changes. I would think that making the hydrogen price in Electrolyzer.csv higher and the investment cost lower should lead to more electrolyzer capacity built, but instead it leads to no solution. I'll keep working on it but appreciate any suggestions you have.

I am trying to run cases similar to the recent paper "Understanding the Role and Design Space of Demand Sinks in Low-carbon Power Systems". If you happened to have example files like the ones used in that analysis, I'd greatly appreciate the headstart.

Joe Rodden
Co-founder & CEO
Lydian ( https://www.lydianlabsinc.com/ )
630-215-6597

**Comment by qluo0320github** [comment] 2024-08-26 15:12
Hi @joe-rodden1, did you see those weird results from GenX example cases? If so, can you share the modified inputs you are using? I do not think changing costs assumptions would result in "no solution". Did you find your model infeasible? If so, can you add "ComputeConflicts: 1" to genx_settings.yml get the conflicts? Also, making the hydrogen price in Electrolyzer.csv higher and the investment cost lower does not necessarily lead to more electrolyzer capacity built because electrolyzers are built to meet hydrogen demand. Only when hydrogen prices are high enough that it has net revenue, the system may choose to build more electrolyzer capacity than what is needed to meet hydrogen demand.

**Comment by joe-rodden1** [comment] 2024-08-26 21:42
Hi there,

I am looking at example case 2. The case runs totally fine as-is. However, the model doesn't solve when I simply reduce the energy demand and investment cost of the electrolyzer resources and increase the selling price (obviously from the energy consumption figure, this is no longer H2 but a generalized flexible asset). These are the only changes made. While I do not necessarily expect predictable/monotonic behavior in running these, I agree it's puzzling that just changing the costs and value would cause an infeasible.

Unfortunately I do not have Gurobi or CPLEX licenses and don't think I can use ComputeConflicts without them, unless my understanding is wrong.

(Run settings are for the successful case, obviously, but in case you need my system specs).

Thanks,

Joe

Joe Rodden
Co-founder & CEO
Lydian ( https://www.lydianlabsinc.com/ )
630-215-6597

**Comment by joe-rodden1** [comment] 2024-08-27 01:06
Hello,

Just want to update that I've gotten my hands on a CPLEX license and have gotten this working for various investment cost assumptions between 75k and 125k/MW-yr. Below that, I'm still getting errors but I have a feeling that's because there are no maximum capacity constraints in the example case and when the resource gets cheap enough, it wants to build it in infinite amounts. I will play around with more reasonable constraints but feel free to close this out for now.

Thanks for all your help.

Joe

Joe Rodden
Co-founder & CEO
Lydian ( https://www.lydianlabsinc.com/ )
630-215-6597

**Comment by qluo0320github** [comment] 2024-08-27 01:11
Yes, this is highly possible. Thanks for letting us know. Best of luck with
your cases!

**Comment by lbonaldo** [comment] 2024-08-27 15:04
Thank you, @joe-rodden1, for opening this issue! I'm glad to hear the examples are running fine. I'll go ahead and close this issue as resolved for now.

**Closed by lbonaldo** 2024-08-27 15:04 UTC
Labels: bug
